# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd97a8d00640656e6af2c782d9de63e3dcabc5faaa17b96e1d73a86b826a80b6827d8c0872f69cdc45f6efb22cefba1502fc7878bc4553e8c71b625bfbc0e95

test:
  secret_key_base: 32f610913c301924fe7ef6efef006037683373f9b3f555909457384c97e1d97ac09b41a2b983ed9375d79084ec8eaa378cb20f2d1168710fca1bac989d110b76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
